### ISSUE TITLE
support github docs folder

### ISSUE THREAD

**Issue by yisar** [denoland/deploy_examples#18]
Just like GitHub pages, sometimes we just use the docs folder instead of the entire GitHub repository.

**Comment by satyarohith** [comment]
@yisar Can you please be more explicit?

**Comment by yisar** [comment]
@satyarohith Well, I'll try to explain.

Currently, I use deno deploy to deploy fre's documents website, which proxy fetch events to access GitHub enter file.

```js
if (pathname === 'readme.md'){
  const data = await fetch('yisar.github.io/fre' + pathname).then(res=>res.text()).then(data=>data)
  return new Response(data)
}
```
Is there a better way, such as using relative paths?

```js
import data from './readme.md'
```
Because in fact, these files should also be downloaded (not JS files), you may need to convert them to JS binary format?

**Comment by satyarohith** [comment]
> Is there a better way, such as using relative paths?

You need to `fetch()` the resources as you did in the above example. Here's a guide that explains how to serve relative assets: https://deno.com/deploy/docs/serve-static-assets.
