### ISSUE TITLE
information about denodeploy executable is not provided

### ISSUE THREAD

**Issue by fusionstrings** [denoland/deploy_examples#7]
I suspect that the denodeploy executable is following https://github.com/lucacasonato/deploy_examples/blob/main/tools/runtime.js

but in [Run offline](https://github.com/denoland/deploy_examples/tree/main/json_html#run-offline) sections in the examples provided do not mention details of how to obtain the `denodeploy` executable.

**Comment by satyarohith** [comment]
You can install the CLI from https://github.com/denoland/deployctl
